### ISSUE TITLE
gromacs test runs out of memory

### ISSUE THREAD

**Issue by ladinesa** [nomad-coe/atomistic-parsers#7]
@JFRudzinski I commented out test_radius_of_gyration in gromacs tests because it is cosuming too much memory. Can you please have a look at this?

**Comment by JFRudzinski** [comment]
Yes, I will take a look tomorrow and get back to you.

**Comment by JFRudzinski** [comment]
I checked to make sure nothing strange was going on within the calculation of the radius of gyration. It appears that the memory usage (I saw ~2gb in my profiling) is simply due to the "normal" processing of this somewhat large system. I don't know how you would run out of memory though, I can run the tests perfectly fine on my laptop.

In any case, I will work on constructing a smaller system / shorter simulation for testing purposes and replace the test. 

I will also plan to look a bit closer into the various functions that I implemented and try to make sure that nothing funny is going on. Please leave this issue open for now until I run some more tests.

**Comment by JFRudzinski** [comment]
@ladinesa : Please re-check this memory issue using the branch from Issue #13 . I think this may have fixed the problem.

**Comment by JFRudzinski** [comment]
@ladinesa: Did you confirm that the memory issue is fixed? Can we close this issue now?

**Comment by ladinesa** [comment]
It still takes ca. 2 mins for the test_radius_of_gyration, but at least now my computer does not freeze so we can close this.

**Comment by JFRudzinski** [comment]
hmm, that's strange, it doesn't take so long on my computer, maybe 30s. Well, I can also curate a smaller system for this test at some point. Maybe we should actually leave it open so that I don't forget?

**Comment by JFRudzinski** [comment]
Solved by https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/tree/1490-smaller-test-data-for-md-workflow
